development:
  adapter: mysql2
  encoding: utf8
  database: restaurant_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: restaurant_test
  pool: 5
  username: root
  password: root